package com.example.mybank

import android.app.Activity
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.ActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.compose.rememberNavController
import com.example.mybank.navigation.NavGraph
import com.example.mybank.navigation.Screen
import com.example.mybank.presentation.auth.AuthViewModel
import com.example.mybank.presentation.settings.SettingsViewModel
import com.example.mybank.ui.theme.MyBankTheme
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    
    private lateinit var googleSignInClient: GoogleSignInClient
    
    companion object {
        private const val TAG = "MainActivity"
    }
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // Configure Google Sign-In
        // NOTE: R.string.default_web_client_id is auto-generated by google-services plugin
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id))
            .requestEmail()
            .build()
        
        googleSignInClient = GoogleSignIn.getClient(this, gso)
        
        setContent {
            val settingsViewModel: SettingsViewModel = hiltViewModel()
            val authViewModel: AuthViewModel = hiltViewModel()
            val settingsState by settingsViewModel.uiState.collectAsState()
            
            // Google Sign-In launcher
            val googleSignInLauncher = rememberLauncherForActivityResult(
                contract = ActivityResultContracts.StartActivityForResult()
            ) { result ->
                handleGoogleSignInResult(result, authViewModel)
            }
            
            MyBankTheme(darkTheme = settingsState.isDarkTheme) {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    val navController = rememberNavController()
                    
                    // Provide Google Sign-In client to composables via CompositionLocal
                    CompositionLocalProvider(
                        LocalGoogleSignInClient provides googleSignInClient,
                        LocalGoogleSignInLauncher provides googleSignInLauncher
                    ) {
                        NavGraph(
                            navController = navController,
                            startDestination = Screen.Splash.route
                        )
                    }
                }
            }
        }
    }
    
    /**
     * Handle Google Sign-In result from Activity Result API
     */
    private fun handleGoogleSignInResult(
        result: ActivityResult,
        authViewModel: AuthViewModel
    ) {
        if (result.resultCode == Activity.RESULT_OK) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {
                val account = task.getResult(ApiException::class.java)
                if (account != null) {
                    Log.d(TAG, "Google Sign-In successful: ${account.email}")
                    
                    // Get ID Token and authenticate with Firebase
                    account.idToken?.let { idToken ->
                        authViewModel.signInWithGoogle(idToken)
                    } ?: run {
                        Log.e(TAG, "Google ID Token is null")
                    }
                } else {
                    Log.e(TAG, "Google account is null")
                }
            } catch (e: ApiException) {
                Log.e(TAG, "Google Sign-In failed: ${e.statusCode} - ${e.message}")
                
                // Common error codes:
                // 12501: User cancelled
                // 12502: Network error
                // 10: Developer error (wrong SHA-1 or Google Sign-In not enabled)
                when (e.statusCode) {
                    12501 -> Log.d(TAG, "User cancelled Google Sign-In")
                    12502 -> Log.e(TAG, "Network error during Google Sign-In")
                    10 -> Log.e(TAG, "Developer error: Check SHA-1 fingerprint and Firebase configuration")
                    else -> Log.e(TAG, "Unknown error: ${e.statusCode}")
                }
            }
        } else {
            Log.d(TAG, "Google Sign-In cancelled or failed: ${result.resultCode}")
        }
    }
}

/**
 * CompositionLocal for accessing GoogleSignInClient in Composables
 */
val LocalGoogleSignInClient = staticCompositionLocalOf<GoogleSignInClient?> { null }

/**
 * CompositionLocal for accessing Google Sign-In launcher in Composables
 */
val LocalGoogleSignInLauncher = staticCompositionLocalOf<androidx.activity.result.ActivityResultLauncher<android.content.Intent>?> { null }
